baseurl: "https://curioushieu.com"
languageCode: "en-us"
title: curious hieu
paginate: 6

taxonomies:
  category: categories
  tag: tags


# disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 
  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "curious hieu"
  siteDesc: "thoughts in progress."
  author: "hieu nguyen"


  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 5

  # Show your social information with icon on index bio with `_index.md` content.
  socialOptions:
    email: hieu6n@gmail.com
    linkedin: https://www.linkedin.com/in/hieu6/
    steam:
    twitter:
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: posts
      url: "/posts/"
      weight: 1
  footer:
    - name: copyright © 2022 hieu nguyen
      url: ""

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer: false
      linkify: true

outputs:
  home: ["HTML", "RSS", "JSON"]
