[build]
    publish = "exampleSite/public"

[build.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_THEME = "repo"

[context.production]
    command = "hugo"
    [context.production.environment]
        HUGO_ENV = "production"
